### ISSUE TITLE
debian/control : depends/suggests/recommends joystick

### ISSUE THREAD

**Issue by trebmuh** [ftoledo/pkg-aseqjoy#1]
Hi,
I've got no experience with aseqjoy so it might be a dumby remark I'm doing here. In such a case, please forgive me.

The page https://terminatorx.org/addons/ mention "jscal" to be used to "make full use" of aseqjoy. "jscal" is already packaged in the "joystick" package in debian. Therefore shouldn't "joystick" be mentionned in on of the fields "depends/suggests/recommends" depending on its relative importance with aseqjoy?

Hope that helps,
Olivier

**Comment by trebmuh** [comment]
Sounds like to be the same for "alsa-utils" which brings in the aconnect utility. Isn't it ?

**Comment by ftoledo** [comment]
These packages does not need for use and work .  You can use aseqjoy direct with jack without aconnect. Also, jscal is in the case that you need to callibrate your joystick.  (Some joysticks require calibration to work better). But I think that can add as recommends/suggest as you mean.

Thanks you.

**Comment by trebmuh** [comment]
That was the point yes. Thanks and hope it's been heplfull for you.
